name: spellcheck 
on:
  push:
    paths:
       - '**.adoc'
       - '**.adoc'
       - '**.md'
  workflow_dispatch:
jobs:
  spellchecker:
    uses: devonfw/.github/.github/workflows/devonfw-spellchecker.yml@master
    secrets:
      RESUSABLE_GH_ACTION_TOKEN: ${{ secrets.GHA_TOKEN }}
