name: spellcheck 
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: spellcheck checkout
       uses: actions/checkout@v2
     - uses: igsekor/pyspelling-any@v0.0.2
       name: Spellcheck
