name: Assign Reviewers
on:
  pull_request
  
jobs:
  assign_reviewers:
    runs-on: ubuntu-latest

    steps:
    - name: Assign Reviewers
      # You may pin to the exact commit or the version.
      # uses: ohnogumi/auto-reviewers@0ac93944a127ca1c8ea55bfb3e1e3234229f8549
      uses: ohnogumi/auto-reviewers@v0.0.3
      with:
        token: ${{ secrets.GHA_TOKEN }}
        config: .github/CODEOWNERS
