site:
  title: Devonfw.github.io Docs
  start_page: devonfw.github.io::index.adoc
content:
  sources:
  - url: https://github.com/marvdan/devonfw.github.io.git
    branches: developAntoraGhPage
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

runtime:
  fetch: true
