name: build-and-deploy

on:
  workflow_run:
    workflows: ["Dispcher event on update of devonfw guide"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:     
      - name: Configure git
        run: |
          git config --global fetch.parallel 20

      - name: Clone
        uses: actions/checkout@v1
        with:
          submodules: recursive
          
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: SetupRuby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Install asciidoctor Gem
        run: gem install asciidoctor -v 1.5.7.1

      - name: RenameHomeFiles
        run: |
          cd general-scripts
          npm install
          node renamer.js ../devonfw-guide/ Home .asciidoc
          cd ..

      - name: Solutions from Stack repositories
        run: |
          cd architectures/scripts
          npm install 
          node copySolutionsFromStack.js ../../devonfw-guide
          cd ../../

      - name: Copy pom files for architectures
        run: |
          chmod +x architectures/scripts/copyPomFiles.sh
          architectures/scripts/copyPomFiles.sh
          
      - name: Copy pom files for tutorials
        run: |
          chmod +x wiki-tutorials/scripts/copyPomFiles.sh
          wiki-tutorials/scripts/copyPomFiles.sh

      - name: npm install for architectures
        run: |
          cd architectures/scripts
          npm install
          cd ../../

      - name: Compile sass for architectures
        uses: gha-utilities/sass-build@v0.4.2
        with:
          source: architectures/index.scss
          destination: architectures/index.css
          
      - name: Compile sass for tutorials
        uses: gha-utilities/sass-build@v0.4.2
        with:
          source: wiki-tutorials/index.scss
          destination: wiki-tutorials/index.css

      # asciidoctor tries to load gems dynamically to convert md and scss files.
      # As this gems are not installed this is breaking the build.
      - name: Remove files that are breaking the build
        run: |
          rm architectures/README.md || true
          rm architectures/index.scss || true
          rm wiki-tutorials/README.md || true
          rm wiki-tutorials/index.scss || true

      - name: npm install for asciidoctor-stylesheet
        run: |
          cd asciidoctor-stylesheet
          npm install
          cd ../

      - name: Build
        run: mvn -s ./.m2/unblock-rubygem-proxy-settings.xml clean package
        
      - name: Make IDs unique
        run: |
          cd general-scripts
          npm install
          node correct-ids.js ../target/asciidoc/devonfw-guide/
          cd ..
          
      - name: Remove section numbers
        run: |
          cd general-scripts
          npm install
          node remove-section-numbers.js ../target/asciidoc/
          cd ..

      - name: SplitHtml
        run: |
          asciidoctor -r ./asciidoctor-extensions/multipage-html5-converter.rb -b  multipage_html5 ./target/asciidoc/devonfw-guide/master.asciidoc -a toc=left -a toclevels=3 -a multipage-level=2 -D ./target/generated-docs/website/pages/docs
          cp -avr target/generated-docs/images/ target/generated-docs/website/pages/docs/

      - name: Postprocessing
        run: |
          cd general-scripts
          npm install
          node merger.js ../target/generated-docs/devonfw-guide/master.html ../target/generated-docs/website/pages/docs/ ../target/generated-docs/website/pages/docs/
          node merge-explore.js page-explore.html ../target/generated-docs/website/pages/explore/explore.html ../target/generated-docs/website/pages/explore/ ../target/generated-docs/website/pages/explore/ explore.html
          node video-to-iframe.js ../target/generated-docs/website/pages/resources/resources.html
          node rereferencer/rereference.js ../../target/asciidoc/devonfw-guide/ ../../target/generated-docs/website/pages/docs/
          node highlight-current.js ../target/generated-docs/website
          cd ..
              

      - name: Create output for architectures
        run: |
          chmod +x architectures/scripts/createOutput.sh
          architectures/scripts/createOutput.sh

      - name: Copy output of architectures
        run: |
          cp -avr architectures/target/generated-docs/ target/generated-docs/website/pages/architectures/
          
      - name: Tutorials Checkout
        uses: actions/checkout@v2
        with:
          repository: devonfw-tutorials/tutorials
          path: wiki-tutorials/tutorials
          
      - name: Tutorial Compiler Checkout
        uses: actions/checkout@v2
        with:
          repository: devonfw-tutorials/tutorial-compiler
          path: wiki-tutorials/tutorial-compiler
          
      - name: Test
        run: |
          pwd 
          ls
          pwd
          ls ../
          pwd
          ls ../../
          pwd
          ls wiki-tutorials
          pwd
          ls wiki-tutorials/target
          
      - name: get Parser
        run: |
          pwd
          ls
          #cd wiki-tutorials/tutorial-compiler/engine
          npm install typescript
          pwd
          ls
          pwd
          ls wiki-tutorials/tutorial-compiler/engine
          npm install @types/node
          npx tsc -t es5 wiki-tutorials/tutorial-compiler/engine/parser.ts
          pwd
          ls
          pwd
          ls wiki-tutorials/tutorial-compiler/engine
       
        
      - name: Create output for tutorials
        run: |
          chmod +x wiki-tutorials/scripts/createOutput.sh
          wiki-tutorials/scripts/createOutput.sh
          
      - name: Copy output of tutorials
        run: |
          cp -avr wiki-tutorials/target/generated-docs/ target/generated-docs/website/pages/learning/

      - name: Create output for tutorials
        run: |
          chmod +x wiki-tutorials/scripts/createOutput.sh
          wiki-tutorials/scripts/createOutput.sh

      - name: Copy output of tutorials
        run: |
          cp -avr wiki-tutorials/target/generated-docs/ target/generated-docs/website/pages/learning/

      - name: Build and test search engine
        run: |
          cd website/components/header/search-engine
          npm install
          npm run test
          npm run build
          cp ./dist/bundle.js ../../../../target/generated-docs/website/components/header/search-engine
          ls -al ../../../../target/generated-docs/website/components/header/search-engine
          cd ../../../../

      - name: Reindex
        run: |
          cd search-engine
          npm install
          node ./converter.js ../target/generated-docs/website/pages/docs/  ../architectures/solutions/ ../target/generated-docs/website/components/header/search-engine
          ls -al ../target/generated-docs/website/components/header/search-engine
          cd ../

      - name: Cleanup
        run: |
          cd target/generated-docs
          rm -Rf asciidoctor* documentation pom.xml README.html rubygems*

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./target/generated-docs
