name: Dispcher event on update of devonfw guide
on:
  repository_dispatch:
    types: [dispatch-update-website]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website
        uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
        with:
          remote: true
      - name: update latest changes of devonfw-guide
        run: |
          cd devonfw-guide/
          git fetch
          git merge origin/master
          cd ..
          git add devonfw-guide
          git commit -m "[DocUpdate]"
          git push origin develop
