name: Broken link check
on:
  workflow_run:
    workflows: ["build-and-deploy"]
    types:
      - completed
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: update
        run: sudo apt-get update
      - name: check if apt can find linkchecker
        run: sudo apt-cache search linkchecker  
      - name: install linkchecker
        run: sudo apt-get install w3c-linkchecker
      - name: start check
        run: |
          checklink -r -s -b https://devonfw.com 
          echo $?
