name: linkchecker

on:
  workflow_run:
    workflows: ["build-and-deploy"]
    types:
      - completed

jobs:
  linkchecker:
    runs-on: ubuntu-latest
    steps:     
      - name: Installation
        run: |
          npm install broken-link-checker -g

      - name: Start the linkchecker
        run: |
           blc https://devonfw.com -ro
   
     


