name: Broken link check

on:
  workflow_run:
    workflows: ["build-and-deploy"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: update
        run: sudo apt-get update
      - name: install linkchecker
        run: sudo apt install linkchecker
      - name: start check
        run: linkchecker https://devonfw.com 

