name: Broken link check

on:
  workflow_run:
    workflows: ["build-and-deploy"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    # steps:
    #   - name: update
    #     run: sudo apt-get update
    #   - name: check if apt can find linkchecker
    #     run: sudo apt-cache search linkchecker  
      - name: install linkchecker
        run: pip3 install git+https://github.com/linkchecker/linkchecker.git
        # run: sudo apt-get install w3c-linkchecker

      - name: start check
        run: linkchecker https://devonfw.com 

