name: Broken link check

on:
  workflow_run:
    workflows: ["build-and-deploy"]
    types:
      - completed

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Check links with linkcheck
        uses: filiph/linkcheck@v2.0.15+1
        with:
          arguments: https://devonfw.com
          recursiveLinks: true 