name: previewPR

on:
  pull_request_target    
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v1        
        #TODO: webseite repo angeben
        with:
          submodules: recursive
          
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{runner.os }}-maven-


      - name: Setup Node
        uses: actions/setup-node@v2


      - name: Solutions from Stack repositories
        run: |
          cd architectures/scripts
          npm install 
          node copySolutionsFromStack.js ../../devonfw-guide
          cd ../../
          
      - name: Copy pom files for architectures
        run: |
          chmod +x architectures/scripts/copyPomFiles.sh
          architectures/scripts/copyPomFiles.sh
          
      - name: npm install for architectures
        run: |
          cd architectures/scripts
          npm install
          cd ../../
          
      - name: Compile sass for architectures
        uses: gha-utilities/sass-build@v0.4.2
        with:
          source: architectures/index.scss
          destination: architectures/index.css


      # asciidoctor tries to load gems dynamically to convert md and scss files.
      # As this gems are not installed this is breaking the build.
      - name: Remove files that are breaking the build
        run: |
          rm architectures/README.md || true
          rm architectures/index.scss || true
          
      - name: Build
        run: mvn -s ./.m2/unblock-rubygem-proxy-settings.xml clean package
