name: Publish to GitHub Pages
on:
  push:
    branches: [developAntoraGhPage]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2            
      - name: Run Antora
        uses: kameshsampath/antora-site-action@v0.2.4
        with:
          antora_playbook: antora-playbook.yml
          
      - name: Change Asciidoc to Adoc
        run: |
          pwd
          ls
          ls solutions
          ls docs/modules/ROOT/pages/cicdgen
          pwd
          ls
          #FOR /R %f IN (*.asciidoc) DO REN "%f" *.adoc
          #pwd
          #ls
          
