name: Publish to GitHub Pages
on:
  push:
    branches: [developAntoraGhPage]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Clone
        uses: actions/checkout@v2
        with:
          repository: MarvDan/devonfw.github.io
          ref: developAntoraGhPage
          submodules: true
          
      - name: Clone devon4j
        uses: actions/checkout@v2
        with:
          repository: devonfw/devon4j
          ref: master
          path: docs/modules/ROOT/pages
          
    
      
      - name: Test2
        run: |
          pwd
          ls docs/modules/ROOT/pages
          
          
      - name: Change Asciidoc to Adoc
        run: |
          find docs/modules/ROOT/pages -depth -name "*.asciidoc" -exec sh -c 'mv "$1" "${1%.asciidoc}.adoc"' _ {} \;

         
      - name: Test1
        run: |
          pwd
          ls docs/modules/ROOT/pages
          
                    
      - name: Run Antora
        uses: kameshsampath/antora-site-action@v0.2.4
        with:
          antora_playbook: docs/antora-playbook.yml
          
      - name: Artifact build upload
        uses: actions/upload-artifact@v2
        with: 
          name: my-artifact
          path: docs/build
#######
         
      - name: Test
        run: |
          pwd
          ls docs
