name: Publish to GitHub Pages
on:
  push:
    branches: [developAntoraGhPage]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Clone
        uses: actions/checkout@v2
        with:
          repository: MarvDan/devonfw.github.io
          ref: developAntoraGhPage
          submodules: true
          
      - name: Change Asciidoc to Adoc
        run: |
          find docs/modules/ROOT/pages -depth -name "*.asciidoc" -exec sh -c 'mv "$1" "${1%.asciidoc}.adoc"' _ {} \;
    #      
     # - name: Run Antora
      #  uses: kameshsampath/antora-site-action@v0.2.4
       # with:
        #  antora_playbook: antora-playbook.yml
         
      - name: Test1
        run: |
          pwd
          ls
       
      - name: Antora
        run: |
         cd docs
         pwd
         ls
         npm i @antora/site-generator-default
         pwd
         ls
         
      - name: Test
        run: |
          pwd
          ls
