name: testParser

on:
  workflow_run:
    workflows: ["Dispcher event on update of devonfw guide"]
    types:
      - completed
  workflow_dispatch: 
  
jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Tutorials checkout
        uses: actions/checkout@v2
        with:
          repo: devonfw-tutorials/tutorials
          path: tutorials
          
      - name: Tutorial Compiler checkout
        uses: actions/checkout@v2
        with:
          repo: devonfw-tutorials/wiki-tutorials
          path: tutorial-compiler
          
      - name: get Parser
        run: |
              pwd
              ls
