name: Update Submodules
env:
  BUILD_USER: ${{ secrets.BUILD_USER }}
  BUILD_USER_EMAIL:  ${{ secrets.BUILD_USER_EMAIL }}
on:
  push:
    branches: [ develop ]
  repository_dispatch:
    types: [dispatch-update-website]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup git user
        run: |
          git config --global user.email ${BUILD_USER_EMAIL}
          git config --global user.name ${BUILD_USER}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          ref: develop
      - name: update latest changes of devonfw-guide
        run: |
          git submodule update --remote
          git add -u
          
          # just commit if there is anything to commit
          git diff --cached --exit-code
          result=${?}
          echo "Exit code diff: $result"
          git status
          if [ ${result} = 0 ]
          then
            echo "Nothing to commit!"
          else
            echo "git commit"
            git commit -m "[DocUpdate]"
            echo "git commit"
            git push origin develop
          fi
